apiVersion: v1
kind: Pod
metadata:
  name: job-pod
spec:
  restartPolicy: Never
  containers:
  - name: job-container
    image: busybox
    command: ["rsync", "-avz", "/data/src/", "/data/dst/"]
  volumes:
  - name: data
    hostPath:
      path: /data
      type: Directory