---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - secretRef:
        name: my-secret
  restartPolicy: Always
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  MY_SECRET_ENV_VAR: YWRtaW4=
type: Opaque